# Generated by Django 5.0.1 on 2024-01-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcstnotification',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='broadcstnotification',
            name='broadcast_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
