# Generated by Django 5.0.1 on 2024-01-16 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('initial_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('tenant_id', models.IntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('booked', 'Booked'), ('rented', 'Rented'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='reserved', max_length=50)),
                ('move_in_date', models.DateField()),
                ('no_of_rooms', models.IntegerField(default=1)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lease_agreement', models.FileField(blank=True, null=True, upload_to='lease_agreements/')),
            ],
        ),
    ]
