apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30200  # Elige un puerto que esté libre en tu máquina
  selector:
    app: elasticsearch