apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-broker:9092
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka-broker
        ports:
        - containerPort: 9092
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: kafka-service
#   name: kafka-service
#   namespace: kafka
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: kafka-service
#   template:
#     metadata:
#       labels:
#         app: kafka-service
#     spec:
#       hostname: kafka-service
#       containers:
#       - name: kafka-container 
#         image: wurstmeister/kafka
#         imagePullPolicy: IfNotPresent
#         env:
#         - name: KAFKA_BROKER_ID
#           value: "1"
#         - name: KAFKA_ZOOKEEPER_CONNECT
#           value: zookeeper-service:2181
#         - name: KAFKA_LISTENERS
#           value: PLAINTEXT://:9092
#         - name: KAFKA_ADVERTISED_LISTENERS
#           value: PLAINTEXT://kafka-broker:9092