# Generated by Django 4.2.7 on 2023-12-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('bed', 'Bed'), ('room', 'Room'), ('house', 'House')], default='House', max_length=50),
        ),
    ]
