# Generated by Django 4.2.9 on 2024-01-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rentalagreement_monthlypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='amount_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
