# Generated by Django 4.2.9 on 2024-01-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_monthlypayment_amount_payable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlypayment',
            old_name='amount_payable',
            new_name='fine',
        ),
    ]
