# Generated by Django 4.2.9 on 2024-01-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_amount_payable_monthlypayment_fine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlypayment',
            old_name='payment_date',
            new_name='due_date',
        ),
    ]
