# Generated by Django 4.2.9 on 2024-01-17 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_monthlypayment_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='property_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
