# Generated by Django 5.0.1 on 2024-01-04 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_timeslot_end_time_remove_timeslot_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletimes',
            name='room_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='ScheduledVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visior_id', models.IntegerField()),
                ('visit_date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.availabletimes')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.timeslot')),
            ],
        ),
    ]
