# Generated by Django 5.0.1 on 2024-01-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_availabletimes_room_id_alter_timeslot_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledvisit',
            old_name='visior_id',
            new_name='visitor_id',
        ),
    ]
