# Generated by Django 5.0.1 on 2024-01-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_visior_id_scheduledvisit_visitor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledvisit',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
