apiVersion: apps/v1
kind: Deployment
metadata:
  name: property
  labels: 
    app: property

spec: 
  replicas: 2
  selector:
    matchLabels:
      app: property
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata: 
      labels: 
        app: property
    spec:
      containers:
        - name: property
          image: adhil28/property
          envFrom:
            - configMapRef:
                name: property-configmap
            - secretRef:
                name: property-secret