apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: efs-access-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: efs-access-role
  apiGroup: rbac.authorization.k8s.io
