# Generated by Django 5.0 on 2023-12-13 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('initial_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('tenant_id', models.IntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='reserved', max_length=50)),
                ('no_of_rooms', models.IntegerField()),
            ],
        ),
    ]
