# Generated by Django 5.0 on 2023-12-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablerooms',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
