# Generated by Django 5.0 on 2023-12-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_booking_lease_agreement_booking_monthly_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
