# Generated by Django 5.0 on 2023-12-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_booking_no_of_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
