# Generated by Django 5.0 on 2024-01-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_booking_move_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('booked', 'Booked'), ('rented', 'Rented'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='reserved', max_length=50),
        ),
    ]
