# Generated by Django 5.0 on 2024-01-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableRooms',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
