# Generated by Django 5.0 on 2024-01-16 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_availablerooms_image_availablerooms_property_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main_app.availablerooms'),
        ),
    ]
