# Generated by Django 5.0 on 2024-02-19 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_booking_room_id_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablerooms',
            name='available_quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='availablerooms',
            name='initial_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
