# Generated by Django 5.0 on 2024-02-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_availablerooms_available_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='room_id',
            field=models.IntegerField(default=65),
            preserve_default=False,
        ),
    ]
